version: "2"
services:
  zikchat:
    build: ./zik-chat
    restart: always
  zikproxy:
    build: ./zik-proxy
    restart: always
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - zikchat
      - zikproxy
    restart: always